/*
 * Auto-generated by Frida. Please modify to match the signature of memcmp.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    try {
      var a = args[0];
      var b = args[1];
      var n = args[2].toInt32();
      var len = n > 32 ? 32 : n;
      var ba = Memory.readByteArray(a, len);
      var bb = Memory.readByteArray(b, len);
      function toHex(buf){
        var u8 = new Uint8Array(buf);
        var out = [];
        for (var i=0;i<u8.length;i++){ out.push(('0'+u8[i].toString(16)).slice(-2)); }
        return out.join(' ');
      }
      log('memcmp(n=' + n + ') a=' + toHex(ba) + ' b=' + toHex(bb));
    } catch (e) {
      log('memcmp(<unreadable>)');
    }
  },

  onLeave(log, retval, state) {
  }
});
