/*
 * Auto-generated by Frida. Please modify to match the signature of LoadLibraryW.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    try {
      var s = Memory.readUtf16String(args[0]);
      log('LoadLibraryW(' + s + ')');
    } catch (e) {
      log('LoadLibraryW(<unreadable>)');
    }
  },

  onLeave(log, retval, state) {
  }
});
