/*
 * Auto-generated by Frida. Please modify to match the signature of _stricmp.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    try {
      var s1 = Memory.readCString(args[0]);
      var s2 = Memory.readCString(args[1]);
      log('_stricmp(' + s1 + ', ' + s2 + ')');
    } catch (e) {
      log('_stricmp(<unreadable>)');
    }
  },

  onLeave(log, retval, state) {
  }
});
