/*
 * Auto-generated by Frida. Please modify to match the signature of NtMapViewOfSection.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    this.basePtr = args[2];
    this.sizePtr = args[6];
    log('NtMapViewOfSection()');
  },

  onLeave(log, retval, state) {
    try {
      var base = Memory.readPointer(this.basePtr);
      var size = Memory.readU64(this.sizePtr);
      log('NtMapViewOfSection -> base=' + base + ' size=' + size);
    } catch (e) {
      log('NtMapViewOfSection -> <unreadable>');
    }
  }
});
