/*
 * Auto-generated by Frida. Please modify to match the signature of CompareStringW.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    try {
      var s1 = Memory.readUtf16String(args[2]);
      var s2 = Memory.readUtf16String(args[4]);
      log('CompareStringW(' + s1 + ', ' + s2 + ')');
    } catch (e) {
      log('CompareStringW(<unreadable>)');
    }
  },

  onLeave(log, retval, state) {
  }
});
