/*
 * Auto-generated by Frida. Please modify to match the signature of GetProcAddress.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    try {
      var s = Memory.readCString(args[1]);
      log('GetProcAddress(' + s + ')');
    } catch (e) {
      log('GetProcAddress(' + args[1] + ') <unreadable>');
    }
  },

  onLeave(log, retval, state) {
  }
});
