/*
 * Auto-generated by Frida. Please modify to match the signature of connect.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    try {
      var sockaddr = args[1];
      var family = Memory.readU16(sockaddr);
      if (family === 2) { // AF_INET
        var port = Memory.readU16(sockaddr.add(2));
        port = ((port & 0xff) << 8) | (port >> 8);
        var ip = Memory.readU32(sockaddr.add(4));
        var b1 = ip & 0xff;
        var b2 = (ip >> 8) & 0xff;
        var b3 = (ip >> 16) & 0xff;
        var b4 = (ip >> 24) & 0xff;
      log('connect(' + b1+'.'+b2+'.'+b3+'.'+b4 + ':' + port + ')');
      } else {
        log('connect(family=' + family + ')');
      }
    } catch (e) {
      log('connect(sockaddr=' + args[1] + ') <unreadable>');
    }
  },

  onLeave(log, retval, state) {
  }
});
