/*
 * Auto-generated by Frida. Please modify to match the signature of recv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    this.buf = args[1];
    this.len = args[2].toInt32();
    log('recv(len=' + this.len + ')');
  },

  onLeave(log, retval, state) {
    try {
      var n = retval.toInt32();
      if (n > 0 && n < 4096) {
        var data = Memory.readByteArray(this.buf, n);
        var s = '';
        var u8 = new Uint8Array(data);
        for (var i=0;i<u8.length;i++) {
          var c = u8[i];
          s += (c>=32 && c<127) ? String.fromCharCode(c) : '.';
        }
        log('recv -> ' + s);
      }
    } catch (e) {
    }
  }
});
