/*
 * Auto-generated by Frida. Please modify to match the signature of send.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    var buf = args[1];
    var len = args[2].toInt32();
    try {
      if (len > 0 && len < 4096) {
        var data = Memory.readByteArray(buf, len);
        var s = '';
        var u8 = new Uint8Array(data);
        for (var i=0;i<u8.length;i++) {
          var c = u8[i];
          s += (c>=32 && c<127) ? String.fromCharCode(c) : '.';
        }
        log('send(buf=' + buf + ', len=' + len + ') ' + s);
      } else {
        log('send(buf=' + buf + ', len=' + len + ')');
      }
    } catch (e) {
      log('send(buf=' + buf + ', len=' + len + ') <unreadable>');
    }
    try {
      var bt = Thread.backtrace(this.context, Backtracer.ACCURATE)
        .slice(0, 6)
        .map(DebugSymbol.fromAddress)
        .join(' | ');
      log('bt: ' + bt);
    } catch (e) {
      log('bt: <unavailable>');
    }
  },

  onLeave(log, retval, state) {
  }
});
